apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: opa-gatekeeper-controller-manager-service-monitor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: Helm
      app: gatekeeper
      chart: gatekeeper 
      gatekeeper.sh/system: "yes"
      heritage: Helm
      release: gatekeeper
  endpoints:
  - port: metrics