apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: my-nginx
  name: my-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      run: my-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      annotations:
        config.trendyol.com/inject: "true"
      labels:
        run: my-nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
        securityContext:
          privileged: true
      serviceAccountName: default
status: {}
